# config/_default/hugo.toml

baseURL = "https://cybersecurite.demystifiee.fr/"
defaultContentLanguage = "fr"

enableEmoji = true
titleCaseStyle = 'none'  # Don't use capital letters in titles and categories

pagination.pagerSize = 40

relativeURLs = true
publishDir = "../docs"

[imaging]
  anchor = 'Center'

[outputs]
  home = ["HTML", "RSS", "JSON"]
