# config/_default/languages.fr.toml

title = "Cybersécurité Démystifiée"

disabled = false
languageCode = "fr-FR"
languageName = "Français"

[params]
  displayName = "FR"
  isoCode = "fr"
  logo = "/img/logo_light.png"
  secondaryLogo = "/img/logo_dark.png"