# config/_default/menus.fr.toml

[[main]]
  pre = "expand"
  name = "Blog"
  pageRef = "/"
  weight = 10

[[main]]
  pre = "bars"
  name = "Catégories"
  pageRef = "categories"
  weight = 20

[[footer]]
  name = "Auteurs"
  pageRef = "authors"

[[footer]]
  name = "Étiquettes"
  pageRef = "tags"
