# config/_default/menus.fr.toml

[[main]]
  pre = "expand"
  name = "Articles CISSP"
  pageRef = "/articles/cissp"
  weight = 10

[[main]]
  pre = "expand"
  name = "Security and Risk Management"
  pageRef = "/articles/cissp/i/"
  weight = 10
  parent = "Articles CISSP"

[[main]]
  pre = "expand"
  name = "Asset Security"
  pageRef = "/articles/cissp/ii/"
  weight = 20
  parent = "Articles CISSP"

[[footer]]
  name = "Auteurs"
  pageRef = "authors"

[[footer]]
  name = "Étiquettes"
  pageRef = "tags"
